# Generated by Django 4.2.9 on 2024-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                default="@tdryn4ik", max_length=25, verbose_name="Чат ID пользователя"
            ),
            preserve_default=False,
        ),
    ]
