# Generated by Django 4.2.9 on 2024-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                default=60, verbose_name="время требующееся на выполнение действия"
            ),
        ),
    ]
