# Generated by Django 4.2.9 on 2024-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_habit_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                default="отдыхаю", max_length=255, verbose_name="действие"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="периодичность в днях"
            ),
        ),
    ]
